version: "2"
volumes:
  ubuntu-openssh-home: {}
services:
  ubuntu-openssh:
    image: "templesofsyrinx/ubuntu-sshd:18.04"
    network_mode: "bridge"
    ports:
    - "$PORT:2222"
    volumes:
      - ubuntu-openssh-home:/home
