version: '2'
services:
  ubuntu-openssh:
    image: "templesofsyrinx/ubuntu-sshd:18.04"
    ports:
    - "$PORT:2222"
    volumes:
      - type: volume
        source: ubuntu-openssh-home
        target: /home
volumes:
  ubuntu-openssh-home: {}
